/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_appsync_graphqlEndpoint": "https://r7aacxomyvaqtdx6jxzgi6be2e.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-7ykif2bor5cz3dgip5hrwgsmke",
    "aws_cloud_logic_custom": [
        {
            "name": "restaurantRestApi",
            "endpoint": "https://cqsxbesjv1.execute-api.eu-west-3.amazonaws.com/dev",
            "region": "eu-west-3"
        }
    ]
};


export default awsmobile;
